### ISSUE TITLE
add rejected, requested and accepted boolean column in bookings table

### ISSUE THREAD

**Issue by Teleri** [rosemaryakl/BEYOND_RENTALS#29]
We need a renter to be able to send a request, which places the booking in a requested state. If the booking is requested, the owner CAN accept or reject, and once they have done so, the booking accepted or rejected is changed to true.

Let me know your thoughts

**Comment by mberthier** [comment]
In that case status should accept an array ("requested", "accepted",  "declined")

It will be requested by default.

The owner will have 2 buttons one to accept and an other one to reject. Once one of the button is clicked, they should both disappear and the status should be updated.

**Comment by Teleri** [comment]
Can you create columns with arrays? 

If so that could work too

**Comment by mberthier** [comment]
No it would be a string, default "requested"

However, we can have array with only the values representing the status of a booking

**Comment by Teleri** [comment]
Yer but in the table, is the value an array, which contains 3 strings?

**Comment by Teleri** [comment]
For now we'll leave this for next week, but not for today's demo
