### ISSUE TITLE
Bookings should not be nested in Planets

### ISSUE THREAD

**Issue by mberthier** [rosemaryakl/BEYOND_RENTALS#30]
We should be able to access bookings_path which will show only the bookings relevant to the user. 

Not for a specific planet but all bookings, since a user should be able to own multiple planets or rent multiple ones.

In order to do that we shouldn't nest bookings in planets.

**Comment by Teleri** [comment]
We can just add a path for index of all current_user's bookings as well

**Comment by Teleri** [comment]
FYI working on this now to only show the owner's bookings (i.e. ones they can accept), or for a renter, the ones that they've requested
