### ISSUE TITLE
New Feature: notification for bookings

### ISSUE THREAD

**Issue by Teleri** [rosemaryakl/BEYOND_RENTALS#54]
If the booking is accepted, there should be a notification of some kind, or a front end change to show that without going onto the booking index page

**Comment by Teleri** [comment]
Possibly https://github.com/simukappu/activity_notification#getting-started

**Comment by mberthier** [comment]
Should we try to implement what was taught on AJAX on rails lecture?

**Comment by Teleri** [comment]
Yer I was thinking that, let's discuss later how we could use it, as we would still need to figure out how to listen for the changed status.

Alex mentioned using this https://guides.rubyonrails.org/active_record_callbacks.html#updating-an-object

So when we have `@booking.update` somewhere, we then have the after_update calling a function that changes a new column `notification` from `false` to `true`, and some front end on the navbar perhaps, will have an if statement changing some css (similarly like the icons for planets).
