### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by mberthier** [rosemaryakl/BEYOND_RENTALS#56]

**Comment by mberthier** [comment]
no lorem ipsum on home page

**Comment by mberthier** [comment]
1. Style the NavBar, replace the LeWagon Logo by something custom.
2. Remove unnecessary links i.e Book & about
3. Remove underline on all links (request from Alex)
4. Replace all Lorem Ipsum by real text

**Comment by rosemaryakl** [comment]
Style the NavBar, replace the LeWagon Logo by something custom. ( done )
Remove unnecessary links i.e Book & about ( done)
Remove underline on all links (request from Alex) (done ) 
Replace all Lorem Ipsum by real text ( in process)

**Comment by rosemaryakl** [comment]
NAVBAR HTML:

`  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
              <div class="header--sticky__desktop  ">
              <a href="/" class="headline2  header__logo__link "> BEYOND RENTALS </a>

            </div>

  <%= link_to root_path, class: "navbar-brand" do %>
    <% end %>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home",  root_path, class: "header__account type" %>
        </li>
        &nbsp; &nbsp;
        <li class="nav-item">
          <%= link_to " Messages", "#", class: "header__account type" %>
        </li>
        &nbsp;
        &nbsp;

     
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "header__account type" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>



`

**Comment by rosemaryakl** [comment]
NAVBAR CSS: 
```@import "pages/index";

.navbar-lewagon {
  justify-content: space-between;
  background: white;
}

.navbar-lewagon .navbar-collapse {
  flex-grow: 0;
}

.navbar-lewagon .navbar-brand img {
  width: 40px;
}


.headline2 {
  font-family: SWBaboonType-ExtraBold, helvetica, serif;

  font-size:30px;
    justify-content: space-between;
    color: #000CDD;
}

a {
  color: #000cdd;
  font-family: SWBaboonType-Light,helvetica,sans-serif;
  font-size: .9em;
  font-weight: normal;
  line-height: 1.55556;
  text-decoration: underline;
  transition: color .3s cubic-bezier(.23,1,.32,1);
  width: auto;
 text-decoration:none;
}



a:hover{
  color: #FB3B15;
 text-decoration:none;
}

.type {
  font-family: SWBaboonType-Light,helvetica,sans-serif;
  font-size: 20px;
  font-weight: normal;
  line-height: 25px;
  margin: 0;
  text-decoration:none;
}
.type:hover{
  color: #FB3B15;
  text-decoration: none;
}

 .dropdown-item:hover{
  color: #FB3B15;
  text-decoration: none;
}

```

**Comment by rosemaryakl** [comment]
All done
