### ISSUE TITLE
Planet Show Page

### ISSUE THREAD

**Issue by mberthier** [rosemaryakl/BEYOND_RENTALS#57]

**Comment by mberthier** [comment]
Create a partial for the Add a Booking and render it on planet show page

**Comment by mberthier** [comment]
date picker, flat picker for new booking

https://github.com/Nerian/bootstrap-datepicker-rails
or
https://github.com/zokioki/flatpickr-rails

**Comment by Teleri** [comment]
I'll start with this

**Comment by Teleri** [comment]
I will include a transition of some kind for the front end next week

https://cloudfour.com/thinks/transitioning-hidden-elements/
https://codepen.io/phebert/pen/yLybwWY

**Comment by Teleri** [comment]
#63
